invitados = ["Nikola Tesla", "Alan Turing", "Friedrich Gauss"]
print(f"Querido {invitados[0]}, espero que te encuentres bien. Te invito a mi fiesta.")
print(f"Hola, {invitados[1]}, ¿me haría el favor de venir a la fiesta, por favor?")
print(f"Buenas, {invitados[2]}, si tiene tiempo, venga a mi fiesta, por favor")
print(invitados.pop(2))
invitados.append("Bill Gates")
print(f"Querido {invitados[0]}, espero que te encuentres bien. Te invito a mi fiesta.")
print(f"Hola, {invitados[1]}, ¿me haría el favor de venir a la fiesta, por favor?")
print(f"Buenas, {invitados[2]}, si tiene tiempo, venga a mi fiesta, por favor")
print("¡Buenas noticias!, encontré una mesa más grande.")
invitados.insert(0, "Linus Torvalds")
invitados.insert(2, "René Descartes")
invitados.append("Deisler Fonseca")
print(f"Querido {invitados[0]}, espero que te encuentres bien. Te invito a mi fiesta.")
print(f"Hola, {invitados[1]}, ¿me haría el favor de venir a la fiesta, por favor?")
print(f"Buenas, {invitados[2]}, si tiene tiempo, venga a mi fiesta, por favor.")
print(f"¿Cómo estás, {invitados[3]}? Te invito a mi fiesta.")
print(f"{invitados[4]}, le comunico que está cordialmente invitado a mi fiesta.")
print(f"{invitados[5]}, hoy habrá una fiesta a la que está invitado, por si desea asistir.")
print("I'm so sorry, but now I can invite only 2 people.")
print(f"Lo siento, {invitados.pop()}, pero ya no estás invitado.")
print(f"Hola, {invitados.pop()}, lamento informarle que ya no hay espacio para usted en la fiesta.")
print(f"Señor {invitados.pop()}, tristemente nos quedamos sin espacio para usted.")
print(f"{invitados.pop()}, ya no hay espacio para usted en la fiesta.")
print(f"Buenas noticias, {invitados[0]}, queda espacio para usted.")
print(f"{invitados[1]}, su espacio sigue disponible.")
del invitados[0]
del invitados[0]
print(invitados)
print(len(invitados))