lugares = ["Italia", "Islandia", "Grecia", "Japón", "Chile"]
print(lugares)
print(sorted(lugares))
print(lugares)
print(sorted(lugares, reverse=True))
print(lugares)
lugares.reverse()
print(lugares)
lugares.reverse()
print(lugares)
lugares.sort()
print(lugares)
lugares.sort(reverse=True)
print(lugares)


lenguajes_programación = ["Python", "Java", "Java Script", "C++"]
print("Algunos lenguajes en orden alfabético son:")
print(sorted(lenguajes_programación))
lenguajes_programación.sort()
print(lenguajes_programación)
print("Y al revés del orden alfabético sería:")
print(sorted(lenguajes_programación, reverse=True))
lenguajes_programación.sort(reverse=True)
print(lenguajes_programación)
lenguajes_programación.sort()
lenguajes_programación.reverse()
print(lenguajes_programación)
print("La cantidad de elementos que tiene la lista es:")
print(len(lenguajes_programación))